name: "Lint"
description: "Run lint checks"

inputs:
  node-version:
    description: "Node.js version"
    required: false
    default: "18.x"

runs:
  using: "composite"
  steps:
    - name: Setup Environment
      uses: ./.github/actions/setup
      with:
        node-version: ${{ inputs.node-version }}

    - name: Run lint
      shell: bash
      run: |
        npm install
        npm run lint
