using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace AntDesign.SourceGenerators;

[Generator]
public sealed class PropsGenerator : ISourceGenerator
{
    public void Initialize(GeneratorInitializationContext context)
        => context.RegisterForSyntaxNotifications(static () => new Receiver());

    public void Execute(GeneratorExecutionContext context)
    {
        if (context.SyntaxReceiver is not Receiver receiver)
        {
            return;
        }

        var processedComponents = new HashSet<INamedTypeSymbol>(SymbolEqualityComparer.Default);
        foreach (var declaration in receiver.Candidates)
        {
            var model = context.Compilation.GetSemanticModel(declaration.SyntaxTree);
            if (model.GetDeclaredSymbol(declaration) is not INamedTypeSymbol component ||
                component.IsAbstract ||
                component.DeclaredAccessibility != Accessibility.Public ||
                component.ContainingType is not null ||
                component.GetAttributes().Any(attribute => attribute.AttributeClass?.ToDisplayString() == "AntDesign.SkipComponentPropsGenerationAttribute") ||
                !component.DeclaringSyntaxReferences.All(reference =>
                    reference.GetSyntax() is ClassDeclarationSyntax typeDeclaration &&
                    typeDeclaration.Modifiers.Any(modifier => modifier.IsKind(Microsoft.CodeAnalysis.CSharp.SyntaxKind.PartialKeyword))) ||
                !InheritsAntComponentBase(component))
            {
                continue;
            }

            if (!processedComponents.Add(component))
            {
                continue;
            }

            var properties = component.GetMembers()
                .OfType<IPropertySymbol>()
                .Where(property => property.DeclaredAccessibility == Accessibility.Public &&
                                   !property.IsStatic &&
                                   property.SetMethod is not null &&
                                   property.GetAttributes().Any(attribute =>
                                       attribute.AttributeClass?.ToDisplayString() == "Microsoft.AspNetCore.Components.ParameterAttribute"))
                .ToArray();

            var propsName = component.Name + "Props";
            var propsMetadataName = component.ContainingNamespace.IsGlobalNamespace
                ? propsName
                : component.ContainingNamespace.ToDisplayString() + "." + propsName;
            if (properties.Length == 0 || context.Compilation.GetTypeByMetadataName(propsMetadataName) is not null)
            {
                continue;
            }

            context.AddSource($"{component.ContainingNamespace.ToDisplayString().Replace('.', '_')}_{component.Name}_{component.Arity}.Props.g.cs", Source(component, propsName, properties, !HasPropertyInBaseTypes(component, "Id"), !HasPropertyInBaseTypes(component, "CascadingPropsCollection")));
        }
    }

    private static bool InheritsAntComponentBase(INamedTypeSymbol component)
    {
        for (var type = component.BaseType; type is not null; type = type.BaseType)
        {
            if (type.ToDisplayString() == "AntDesign.AntComponentBase")
            {
                return true;
            }
        }

        return false;
    }

    private static bool HasPropertyInBaseTypes(INamedTypeSymbol component, string name)
    {
        for (var type = component.BaseType; type is not null; type = type.BaseType)
        {
            if (type.GetMembers(name).OfType<IPropertySymbol>().Any())
            {
                return true;
            }
        }

        return false;
    }

    private static string Source(INamedTypeSymbol component, string propsName, IEnumerable<IPropertySymbol> properties, bool generateId, bool generatePropsCollection)
    {
        var cascadingPropsName = "Cascading" + component.Name + "Props";
        var source = new StringBuilder();
        source.AppendLine("// <auto-generated />");
        source.AppendLine("#nullable enable");
        source.Append("namespace ").Append(component.ContainingNamespace.ToDisplayString()).AppendLine();
        source.AppendLine("{");
        source.Append("    public sealed class ").Append(propsName);
        AppendTypeParameters(source, component);
        source.AppendLine(" : global::AntDesign.ComponentProps");
        AppendConstraints(source, component);
        source.AppendLine("    {");
        foreach (var property in properties)
        {
            var type = property.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            var field = "_" + char.ToLowerInvariant(property.Name[0]) + property.Name.Substring(1);
            source.Append("        private ").Append(type).Append(' ').Append(field).AppendLine(";");
            source.Append("        public ").Append(type).Append(' ').Append(property.Name)
                .Append(" { get => ").Append(field).Append("; set => SetProperty(ref ").Append(field)
                .Append(", value, nameof(").Append(property.Name).AppendLine(")); }");
        }
        source.AppendLine("    }");
        source.AppendLine();
        source.Append("    public partial class ").Append(component.Name);
        AppendTypeParameters(source, component);
        source.Append(" : global::AntDesign.IComponentPropsReceiver");
        AppendConstraints(source, component);
        source.AppendLine();
        source.AppendLine("    {");
        if (generateId)
        {
            source.AppendLine("        [global::Microsoft.AspNetCore.Components.Parameter]");
            source.AppendLine("        public string? Id { get; set; }");
            source.AppendLine();
        }
        source.AppendLine("        [global::Microsoft.AspNetCore.Components.CascadingParameter]");
        source.Append("        public ").Append(propsName);
        AppendTypeParameters(source, component);
        source.Append("? ").Append(cascadingPropsName).AppendLine(" { get; set; }");
        if (generatePropsCollection)
        {
            source.AppendLine();
            source.AppendLine("        [global::Microsoft.AspNetCore.Components.CascadingParameter]");
            source.AppendLine("        public global::AntDesign.ComponentPropsCollection? CascadingPropsCollection { get; set; }");
        }
        source.AppendLine();
        source.AppendLine("        void global::AntDesign.IComponentPropsReceiver.ApplyCascadingProps()");
        source.AppendLine("        {");
        source.Append("            ApplyProps(").Append(cascadingPropsName).AppendLine(");");
        source.Append("            ApplyProps(CascadingPropsCollection?.GetDefault<").Append(propsName);
        AppendTypeParameters(source, component);
        source.AppendLine(">());");
        source.Append("            ApplyProps(CascadingPropsCollection?.Get<").Append(propsName);
        AppendTypeParameters(source, component);
        source.AppendLine(">(Id));");
        source.AppendLine();
        source.Append("            void ApplyProps(").Append(propsName);
        AppendTypeParameters(source, component);
        source.AppendLine("? props)");
        source.AppendLine("            {");
        source.AppendLine("            if (props is not null)");
        source.AppendLine("            {");
        foreach (var property in properties)
        {
            source.Append("                if (props.IsSet(nameof(").Append(propsName);
            AppendTypeParameters(source, component);
            source.Append('.').Append(property.Name).AppendLine(")))");
            source.Append("                    ").Append(property.Name).Append(" = props.").Append(property.Name).AppendLine(";");
        }
        source.AppendLine("            }");
        source.AppendLine("            }");
        source.AppendLine("        }");
        source.AppendLine("    }");
        source.AppendLine("}");
        return source.ToString();
    }

    private static void AppendTypeParameters(StringBuilder source, INamedTypeSymbol component)
    {
        if (component.TypeParameters.Length > 0)
        {
            source.Append('<').Append(string.Join(", ", component.TypeParameters.Select(parameter => parameter.Name))).Append('>');
        }
    }

    private static void AppendConstraints(StringBuilder source, INamedTypeSymbol component)
    {
        foreach (var parameter in component.TypeParameters)
        {
            var constraints = new List<string>();
            if (parameter.HasReferenceTypeConstraint) constraints.Add("class");
            if (parameter.HasValueTypeConstraint) constraints.Add("struct");
            constraints.AddRange(parameter.ConstraintTypes.Select(type => type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)));
            if (parameter.HasConstructorConstraint) constraints.Add("new()");
            if (constraints.Count > 0)
            {
                source.Append(" where ").Append(parameter.Name).Append(" : ").Append(string.Join(", ", constraints));
            }
        }
        source.AppendLine();
    }

    private sealed class Receiver : ISyntaxReceiver
    {
        public List<ClassDeclarationSyntax> Candidates { get; } = new();

        public void OnVisitSyntaxNode(SyntaxNode syntaxNode)
        {
            if (syntaxNode is ClassDeclarationSyntax declaration)
            {
                Candidates.Add(declaration);
            }
        }
    }
}
