name: Release antdv5 package

env:
  Version: 2.0.0
  NUGET_API_KEY: ${{secrets.NUGET_API_KEY}}

on:
  push:
    branches:
      - compatibility-v5

jobs:
  nightly-build:
    runs-on: ubuntu-latest
    if: github.repository_owner == 'ant-design-blazor'

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Setup .NET SDKs
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            3.1.x
            5.0.x
            6.0.x
            7.0.x
            8.0.x
            9.0.x

      - uses: actions/setup-node@v1
        with:
          node-version: "16.x"

      - name: Check Building ⚙
        run: |
          dotnet build

      - name: Package Nightly Nuget 📦
        run: |
          npm i
          SUFFIX=`date "+%y%m%d%H%M%S"`
          dotnet build
          dotnet pack components/AntDesign.csproj /p:PackageVersion=$Version-nightly-${SUFFIX} -c Release -o publish
          dotnet pack src/AntDesign.Style.Generator/AntDesign.Style.Generator.csproj /p:PackageVersion=$Version-v5-${SUFFIX} -c Release -o publish

      - name: Publish to Nuget ✔
        run: |
          dotnet nuget push publish/*.nupkg -s https://api.nuget.org/v3/index.json -k $NUGET_API_KEY --skip-duplicate

