# Each PR will build preview site that help to check code is work as expect.

name: Preview Deploy

on:
  workflow_run:
    workflows: ["Preview Build"]
    types:
      - completed

jobs:
  deploy-site:
    name: deploy preview
    runs-on: ubuntu-latest
    if: >
      github.event.workflow_run.event == 'pull_request' &&
      github.event.workflow_run.conclusion == 'success'
    steps:
      # We need get PR id first
      - name: download pr artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: ${{ github.event.workflow_run.workflow_id }}
          name: pr

      # Save PR id to output and validate it's a number
      - name: save PR id
        id: pr
        run: |
          PR_ID=$(cat pr-id.txt)
          if ! [[ "$PR_ID" =~ ^[0-9]+$ ]]; then
            echo "Invalid PR ID: Not a number"
            exit 1
          fi
          echo "id=$PR_ID" >> $GITHUB_OUTPUT

      # Download site artifact
      - name: download site artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: ${{ github.event.workflow_run.workflow_id }}
          workflow_conclusion: success
          name: site

      - name: upload surge service
        id: deploy
        env:
          PR_ID: ${{ steps.pr.outputs.id }}
        run: |
          export DEPLOY_DOMAIN="https://preview-${PR_ID}-antblazor.surge.sh"
          npx surge --project ./ --domain "${DEPLOY_DOMAIN}" --token ${{ secrets.SURGE_TOKEN }}

      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CF_TOKEN }}
          accountId: ${{ secrets.CF_ID }}
          projectName: 'ant-design-blazor'
          directory: .
          wranglerVersion: '3'

      - name: update status comment
        uses: actions-cool/maintain-one-comment@v1.1.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          body: |
            [<img width="306" src="https://user-images.githubusercontent.com/5378891/72400743-23dbb200-3785-11ea-9d13-1a2d92743846.png">](https://preview-${{ steps.pr.outputs.id }}-antblazor.surge.sh)
            <!-- AUTO_PREVIEW_HOOK -->
          body-include: '<!-- AUTO_PREVIEW_HOOK -->'
          number: ${{ steps.pr.outputs.id }}

      - name: The job has failed
        if: ${{ failure() }}
        uses: actions-cool/maintain-one-comment@v1.1.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          body: |
            <img width="534" src="https://user-images.githubusercontent.com/5378891/75333447-1e63a280-58c1-11ea-975d-235367fd1522.png">
            <!-- AUTO_PREVIEW_HOOK -->
          body-include: '<!-- AUTO_PREVIEW_HOOK -->'
          number: ${{ steps.pr.outputs.id }}

  build-site-failed:
    name: build preview failed
    runs-on: ubuntu-latest
    if: >
      github.event.workflow_run.event == 'pull_request' &&
      github.event.workflow_run.conclusion == 'failure'
    steps:
      # We need get PR id first
      - name: download pr artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: ${{ github.event.workflow_run.workflow_id }}
          name: pr

      # Save PR id to output and validate it's a number
      - name: save PR id
        id: pr
        run: |
          PR_ID=$(cat pr-id.txt)
          if ! [[ "$PR_ID" =~ ^[0-9]+$ ]]; then
            echo "Invalid PR ID: Not a number"
            exit 1
          fi
          echo "id=$PR_ID" >> $GITHUB_OUTPUT

      - name: The job has failed
        uses: actions-cool/maintain-one-comment@v1.1.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          body: |
            <img width="534" src="https://user-images.githubusercontent.com/5378891/75333447-1e63a280-58c1-11ea-975d-235367fd1522.png">
            <!-- AUTO_PREVIEW_HOOK -->
          body-include: '<!-- AUTO_PREVIEW_HOOK -->'
          number: ${{ steps.pr.outputs.id }}
