name: Pull Request Checks

on:
  pull_request:
    branches:
      - master
      - feature

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Setup .NET SDKs
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            3.1.x
            5.0.x
            6.0.x
            7.0.x
            8.0.x
            9.0.x
            10.0.x

      - uses: actions/setup-node@v1
        with:
          node-version: "18.x"

      - name: Check Building ⚙
        run: |
          npm install
          dotnet build

      - name: Test 📝
        run: |
          npm run lint
          dotnet test ./tests/AntDesign.Tests/AntDesign.Tests.csproj --configuration:Release --collect:"XPlat Code Coverage" --settings ./tests/coverage.runsettings --results-directory ./coverage/dotnet/net6 -f net6
          dotnet test ./tests/AntDesign.Tests/AntDesign.Tests.csproj --configuration:Release --collect:"XPlat Code Coverage" --settings ./tests/coverage.runsettings --results-directory ./coverage/dotnet/net8 -f net8
          dotnet test ./tests/AntDesign.Tests/AntDesign.Tests.csproj --configuration:Release --collect:"XPlat Code Coverage" --settings ./tests/coverage.runsettings --results-directory ./coverage/dotnet/net9 -f net9
          dotnet test ./tests/AntDesign.Tests/AntDesign.Tests.csproj --configuration:Release --collect:"XPlat Code Coverage" --settings ./tests/coverage.runsettings --results-directory ./coverage/dotnet/net10 -f net10.0
          npm install ./tests/AntDesign.Tests.Js
          npm --prefix ./tests/AntDesign.Tests.Js run test-cov

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: ./coverage/dotnet
          disable_search: true
          flags: ant-design
          fail_ci_if_error: true

      - name: Export AntDesign coverage report
        uses: actions/upload-artifact@v4
        with:
          name: ant-design-coverage
          path: ./coverage/dotnet/**/coverage.cobertura.xml
